spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: OrderServiceMS
          uri: lb://OrderServiceMS
          predicates:
            - Path=/app/**
        - id: OrderServiceConsumerMS
          uri: lb://OrderServiceConsumerMS
          predicates:
            - Path=/consumer/**